export const INTERACTION_PROMPT_ANIMATION = {
  v: '5.9.1',
  fr: 29.9700012207031,
  ip: 0,
  op: 40.0000016292334,
  w: 640,
  h: 640,
  nm: 'for_display',
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 3,
      nm: 'ヌル 1',
      sr: 1,
      ks: {
        o: { a: 0, k: 0, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [200, 200, 0], ix: 2, l: 2 },
        a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      ip: 0,
      op: 40.0000016292334,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 4,
      nm: 'hand',
      parent: 1,
      sr: 1,
      ks: {
        o: {
          a: 1,
          k: [
            {
              i: { x: [0.34], y: [1] },
              o: { x: [0.03], y: [0.583] },
              t: 0,
              s: [0],
            },
            { t: 7.00000028511585, s: [100] },
          ],
          ix: 11,
        },
        r: {
          a: 1,
          k: [
            {
              i: { x: [0.525], y: [1] },
              o: { x: [0.024], y: [0.292] },
              t: 0,
              s: [0],
            },
            {
              i: { x: [0], y: [0.74] },
              o: { x: [0.739], y: [0] },
              t: 18,
              s: [20],
            },
            { t: 33.0000013441176, s: [-6] },
          ],
          ix: 10,
        },
        p: {
          s: true,
          x: {
            a: 1,
            k: [
              {
                i: { x: [0.672], y: [1] },
                o: { x: [0.155], y: [0.521] },
                t: 0,
                s: [210],
              },
              {
                i: { x: [0.087], y: [1] },
                o: { x: [0.731], y: [0] },
                t: 18,
                s: [258],
              },
              { t: 33.0000013441176, s: [153] },
            ],
            ix: 3,
          },
          y: {
            a: 1,
            k: [
              {
                i: { x: [0.314], y: [1] },
                o: { x: [0.059], y: [0.419] },
                t: 0,
                s: [232.674],
              },
              {
                i: { x: [0.098], y: [0.892] },
                o: { x: [0.844], y: [0] },
                t: 18,
                s: [71.928],
              },
              { t: 33.0000013441176, s: [136.928] },
            ],
            ix: 4,
          },
        },
        a: { a: 0, k: [164, 182.5, 0], ix: 1, l: 2 },
        s: {
          a: 1,
          k: [
            {
              i: { x: [0.496, 0.496, 0.833], y: [1, 1, 1] },
              o: { x: [0.046, 0.046, 0.333], y: [0.597, 0.597, 0] },
              t: 0,
              s: [100, 100, 100],
            },
            {
              i: { x: [0.056, 0.056, 0.833], y: [0.88, 0.88, 1] },
              o: { x: [1, 1, 0.167], y: [0, 0, 0] },
              t: 18,
              s: [120, 120, 100],
            },
            { t: 33.0000013441176, s: [100, 100, 100] },
          ],
          ix: 6,
          l: 2,
        },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ind: 0,
              ty: 'sh',
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [16.722, 41.963],
                    [12.048, -0.453],
                    [23.571, -5.726],
                    [12.829, -5.116],
                    [3.192, 5.529],
                    [0, 0],
                    [12.15, -7.015],
                    [-7.017, -12.153],
                    [0, 0],
                    [1.935, -9.685],
                    [0, 0],
                    [0, 0],
                    [4.66, -12.507],
                    [-12.506, -4.657],
                    [0, 0],
                    [-21.357, -22.566],
                    [-13.472, 7.962],
                    [-29.1, 15.701],
                    [4.744, 11.903],
                  ],
                  o: [
                    [-4.463, -11.201],
                    [-18.035, 0.678],
                    [-15.681, 3.81],
                    [-5.93, 2.365],
                    [0, 0],
                    [-7.017, -12.153],
                    [-12.156, 7.018],
                    [0, 0],
                    [4.939, 8.553],
                    [0, 0],
                    [0, 0],
                    [-12.504, -4.66],
                    [-4.661, 12.505],
                    [0, 0],
                    [28.466, 10.609],
                    [10.757, 11.366],
                    [27.07, -15.999],
                    [11.278, -6.085],
                    [-16.725, -41.964],
                  ],
                  v: [
                    [101.814, -51.876],
                    [74.451, -69.842],
                    [11.465, -61.08],
                    [-31.269, -47.404],
                    [-46.985, -52.813],
                    [-112.241, -165.84],
                    [-146.948, -175.142],
                    [-156.251, -140.431],
                    [-66.778, 14.542],
                    [-62.118, 42.838],
                    [-65.271, 57.212],
                    [-121.044, 35.79],
                    [-152.254, 50.55],
                    [-137.921, 81.074],
                    [-77.104, 104.984],
                    [5.899, 168.176],
                    [47.099, 174.196],
                    [147.176, 116.807],
                    [158.524, 85.342],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: 'パス 1',
              mn: 'ADBE Vector Shape - Group',
              hd: false,
            },
            {
              ty: 'fl',
              c: { a: 0, k: [1, 0.670588235294, 0.231372563979, 1], ix: 4 },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: '塗り 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: { a: 0, k: [163.518, 182.408], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: 'トランスフォーム',
            },
          ],
          nm: 'グループ 1',
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 0,
      op: 40.0000016292334,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 3,
      ty: 4,
      nm: 'シェイプレイヤー 1',
      parent: 2,
      sr: 1,
      ks: {
        o: {
          a: 1,
          k: [
            {
              i: { x: [0.833], y: [0.833] },
              o: { x: [0.167], y: [0.167] },
              t: 28,
              s: [0],
            },
            { t: 29.0000011811942, s: [100] },
          ],
          ix: 11,
        },
        r: { a: 0, k: 6, ix: 10 },
        p: { a: 0, k: [26.151, 30.329, 0], ix: 2, l: 2 },
        a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      shapes: [
        {
          d: 1,
          ty: 'el',
          s: {
            a: 1,
            k: [
              {
                i: { x: [0.165, 0.165], y: [1, 1] },
                o: { x: [0.094, 0.094], y: [0.408, 0.408] },
                t: 29,
                s: [37, 37],
              },
              { t: 36.0000014663101, s: [245, 245] },
            ],
            ix: 2,
          },
          p: { a: 0, k: [0, 0], ix: 3 },
          nm: '楕円形パス 1',
          mn: 'ADBE Vector Shape - Ellipse',
          hd: false,
        },
        {
          ty: 'fl',
          c: {
            a: 0,
            k: [0.470588237047, 0.490196079016, 0.57647061348, 1],
            ix: 4,
          },
          o: { a: 0, k: 25, ix: 5 },
          r: 1,
          bm: 0,
          nm: '塗り 1',
          mn: 'ADBE Vector Graphic - Fill',
          hd: false,
        },
      ],
      ip: 0,
      op: 40.0000016292334,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
}
export const LOADING_ANIMATION = {
  v: '5.7.1',
  fr: 25,
  ip: 0,
  op: 71,
  w: 1100,
  h: 1100,
  nm: 'Comp 1',
  ddd: 0,
  assets: [
    {
      id: 'comp_0',
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 4,
          nm: '1',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 0,
              k: 0,
              ix: 10,
              x: 'var $bm_rt;\n$bm_rt = $bm_mul(time, 100);',
            },
            p: { a: 0, k: [550, 555, 0], ix: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [86.765, 86.765, 100], ix: 6 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  d: 1,
                  ty: 'el',
                  s: { a: 0, k: [816, 816], ix: 2 },
                  p: { a: 0, k: [0, 0], ix: 3 },
                  nm: 'Trazado elíptico 1',
                  mn: 'ADBE Vector Shape - Ellipse',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: { a: 0, k: [0, 0.086274509804, 0.596078431373, 1], ix: 3 },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 150, ix: 5 },
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  bm: 0,
                  nm: 'Trazo 1',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transformar',
                },
              ],
              nm: 'Elipse 1',
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'tm',
              s: { a: 0, k: 0, ix: 1 },
              e: { a: 0, k: 10, ix: 2 },
              o: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833], y: [0.833] },
                    o: { x: [0.167], y: [0.167] },
                    t: 0,
                    s: [720],
                  },
                  { t: 75, s: [800] },
                ],
                ix: 3,
              },
              m: 1,
              ix: 2,
              nm: 'Recortar trazados 1',
              mn: 'ADBE Vector Filter - Trim',
              hd: false,
            },
          ],
          ip: 0,
          op: 125,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 4,
          nm: '2',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 0,
              k: -265.132,
              ix: 10,
              x: 'var $bm_rt;\n$bm_rt = $bm_mul(time, 100);',
            },
            p: { a: 0, k: [550, 555, 0], ix: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [86.765, 86.765, 100], ix: 6 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  d: 1,
                  ty: 'el',
                  s: { a: 0, k: [816, 816], ix: 2 },
                  p: { a: 0, k: [0, 0], ix: 3 },
                  nm: 'Trazado elíptico 1',
                  mn: 'ADBE Vector Shape - Ellipse',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: { a: 0, k: [0, 0.61568627451, 0.674509803922, 1], ix: 3 },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 150, ix: 5 },
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  bm: 0,
                  nm: 'Trazo 1',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transformar',
                },
              ],
              nm: 'Elipse 1',
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'tm',
              s: { a: 0, k: 0, ix: 1 },
              e: { a: 0, k: 10, ix: 2 },
              o: {
                a: 1,
                k: [
                  {
                    i: { x: [0.649], y: [0.84] },
                    o: { x: [0.302], y: [0] },
                    t: 0,
                    s: [0],
                  },
                  {
                    i: { x: [0.825], y: [1] },
                    o: { x: [0.407], y: [1.421] },
                    t: 25,
                    s: [63.439],
                  },
                  { t: 75, s: [80] },
                ],
                ix: 3,
              },
              m: 1,
              ix: 2,
              nm: 'Recortar trazados 1',
              mn: 'ADBE Vector Filter - Trim',
              hd: false,
            },
          ],
          ip: 0,
          op: 125,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 3,
          ty: 4,
          nm: '3',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 0,
              k: -265.132,
              ix: 10,
              x: 'var $bm_rt;\n$bm_rt = $bm_mul(time, 100);',
            },
            p: { a: 0, k: [550, 555, 0], ix: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [86.765, 86.765, 100], ix: 6 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  d: 1,
                  ty: 'el',
                  s: { a: 0, k: [816, 816], ix: 2 },
                  p: { a: 0, k: [0, 0], ix: 3 },
                  nm: 'Trazado elíptico 1',
                  mn: 'ADBE Vector Shape - Ellipse',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [0.352941176471, 0.764705882353, 0.941176470588, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 150, ix: 5 },
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  bm: 0,
                  nm: 'Trazo 1',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transformar',
                },
              ],
              nm: 'Elipse 1',
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'tm',
              s: { a: 0, k: 0, ix: 1 },
              e: { a: 0, k: 10, ix: 2 },
              o: {
                a: 1,
                k: [
                  {
                    i: { x: [0.667], y: [1] },
                    o: { x: [0.333], y: [0] },
                    t: 0,
                    s: [0],
                  },
                  {
                    i: { x: [0.667], y: [1] },
                    o: { x: [0.333], y: [0] },
                    t: 25,
                    s: [100],
                  },
                  { t: 75, s: [80] },
                ],
                ix: 3,
              },
              m: 1,
              ix: 2,
              nm: 'Recortar trazados 1',
              mn: 'ADBE Vector Filter - Trim',
              hd: false,
            },
          ],
          ip: 0,
          op: 125,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 4,
          ty: 4,
          nm: 'Capa de formas 2',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 0,
              k: 0,
              ix: 10,
              x: 'var $bm_rt;\n$bm_rt = $bm_mul(time, 140);',
            },
            p: { a: 0, k: [550, 555, 0], ix: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [86.765, 86.765, 100], ix: 6 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  d: 1,
                  ty: 'el',
                  s: { a: 0, k: [816, 816], ix: 2 },
                  p: { a: 0, k: [0, 0], ix: 3 },
                  nm: 'Trazado elíptico 1',
                  mn: 'ADBE Vector Shape - Ellipse',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [0.886274509804, 0.898039215686, 0.952941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 150, ix: 5 },
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  bm: 0,
                  nm: 'Trazo 1',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transformar',
                },
              ],
              nm: 'Elipse 1',
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'tm',
              s: { a: 0, k: 100, ix: 1 },
              e: { a: 0, k: 0, ix: 2 },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 2,
              nm: 'Recortar trazados 1',
              mn: 'ADBE Vector Filter - Trim',
              hd: false,
            },
          ],
          ip: 0,
          op: 125,
          st: 0,
          bm: 0,
        },
      ],
    },
  ],
  layers: [
    {
      ddd: 0,
      ind: 2,
      ty: 0,
      nm: 'Loading',
      refId: 'comp_0',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [540, 540, 0], ix: 2 },
        a: { a: 0, k: [540, 540, 0], ix: 1 },
        s: { a: 0, k: [90.37, 90.37, 100], ix: 6 },
      },
      ao: 0,
      w: 1080,
      h: 1080,
      ip: 0,
      op: 75,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
}
export const LOADING_ANIMATION_MINI = {
  v: '5.7.1',
  fr: 25,
  ip: 0,
  op: 71,
  w: 1100,
  h: 1100,
  nm: 'Comp 1',
  ddd: 0,
  assets: [
    {
      id: 'comp_0',
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 4,
          nm: '1',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 0,
              k: 0,
              ix: 10,
              x: 'var $bm_rt;\n$bm_rt = $bm_mul(time, 100);',
            },
            p: { a: 0, k: [550, 555, 0], ix: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [86.765, 86.765, 100], ix: 6 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  d: 1,
                  ty: 'el',
                  s: { a: 0, k: [816, 816], ix: 2 },
                  p: { a: 0, k: [0, 0], ix: 3 },
                  nm: 'Trazado elíptico 1',
                  mn: 'ADBE Vector Shape - Ellipse',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: { a: 0, k: [0, 0.086274509804, 0.596078431373, 1], ix: 3 },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 150, ix: 5 },
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  bm: 0,
                  nm: 'Trazo 1',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transformar',
                },
              ],
              nm: 'Elipse 1',
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'tm',
              s: { a: 0, k: 0, ix: 1 },
              e: { a: 0, k: 10, ix: 2 },
              o: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833], y: [0.833] },
                    o: { x: [0.167], y: [0.167] },
                    t: 0,
                    s: [720],
                  },
                  { t: 75, s: [800] },
                ],
                ix: 3,
              },
              m: 1,
              ix: 2,
              nm: 'Recortar trazados 1',
              mn: 'ADBE Vector Filter - Trim',
              hd: false,
            },
          ],
          ip: 0,
          op: 125,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 4,
          nm: '2',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 0,
              k: -265.132,
              ix: 10,
              x: 'var $bm_rt;\n$bm_rt = $bm_mul(time, 100);',
            },
            p: { a: 0, k: [550, 555, 0], ix: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [86.765, 86.765, 100], ix: 6 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  d: 1,
                  ty: 'el',
                  s: { a: 0, k: [816, 816], ix: 2 },
                  p: { a: 0, k: [0, 0], ix: 3 },
                  nm: 'Trazado elíptico 1',
                  mn: 'ADBE Vector Shape - Ellipse',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: { a: 0, k: [0, 0.61568627451, 0.674509803922, 1], ix: 3 },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 150, ix: 5 },
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  bm: 0,
                  nm: 'Trazo 1',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transformar',
                },
              ],
              nm: 'Elipse 1',
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'tm',
              s: { a: 0, k: 0, ix: 1 },
              e: { a: 0, k: 10, ix: 2 },
              o: {
                a: 1,
                k: [
                  {
                    i: { x: [0.649], y: [0.84] },
                    o: { x: [0.302], y: [0] },
                    t: 0,
                    s: [0],
                  },
                  {
                    i: { x: [0.825], y: [1] },
                    o: { x: [0.407], y: [1.421] },
                    t: 25,
                    s: [63.439],
                  },
                  { t: 75, s: [80] },
                ],
                ix: 3,
              },
              m: 1,
              ix: 2,
              nm: 'Recortar trazados 1',
              mn: 'ADBE Vector Filter - Trim',
              hd: false,
            },
          ],
          ip: 0,
          op: 125,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 3,
          ty: 4,
          nm: '3',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 0,
              k: -265.132,
              ix: 10,
              x: 'var $bm_rt;\n$bm_rt = $bm_mul(time, 100);',
            },
            p: { a: 0, k: [550, 555, 0], ix: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [86.765, 86.765, 100], ix: 6 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  d: 1,
                  ty: 'el',
                  s: { a: 0, k: [816, 816], ix: 2 },
                  p: { a: 0, k: [0, 0], ix: 3 },
                  nm: 'Trazado elíptico 1',
                  mn: 'ADBE Vector Shape - Ellipse',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [0.352941176471, 0.764705882353, 0.941176470588, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 150, ix: 5 },
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  bm: 0,
                  nm: 'Trazo 1',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transformar',
                },
              ],
              nm: 'Elipse 1',
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'tm',
              s: { a: 0, k: 0, ix: 1 },
              e: { a: 0, k: 10, ix: 2 },
              o: {
                a: 1,
                k: [
                  {
                    i: { x: [0.667], y: [1] },
                    o: { x: [0.333], y: [0] },
                    t: 0,
                    s: [0],
                  },
                  {
                    i: { x: [0.667], y: [1] },
                    o: { x: [0.333], y: [0] },
                    t: 25,
                    s: [100],
                  },
                  { t: 75, s: [80] },
                ],
                ix: 3,
              },
              m: 1,
              ix: 2,
              nm: 'Recortar trazados 1',
              mn: 'ADBE Vector Filter - Trim',
              hd: false,
            },
          ],
          ip: 0,
          op: 125,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 4,
          ty: 4,
          nm: 'Capa de formas 2',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 0,
              k: 0,
              ix: 10,
              x: 'var $bm_rt;\n$bm_rt = $bm_mul(time, 140);',
            },
            p: { a: 0, k: [550, 555, 0], ix: 2 },
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [86.765, 86.765, 100], ix: 6 },
          },
          ao: 0,
          shapes: [
            {
              ty: 'gr',
              it: [
                {
                  d: 1,
                  ty: 'el',
                  s: { a: 0, k: [816, 816], ix: 2 },
                  p: { a: 0, k: [0, 0], ix: 3 },
                  nm: 'Trazado elíptico 1',
                  mn: 'ADBE Vector Shape - Ellipse',
                  hd: false,
                },
                {
                  ty: 'st',
                  c: {
                    a: 0,
                    k: [0.886274509804, 0.898039215686, 0.952941176471, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 150, ix: 5 },
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  bm: 0,
                  nm: 'Trazo 1',
                  mn: 'ADBE Vector Graphic - Stroke',
                  hd: false,
                },
                {
                  ty: 'tr',
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: 'Transformar',
                },
              ],
              nm: 'Elipse 1',
              np: 3,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: 'ADBE Vector Group',
              hd: false,
            },
            {
              ty: 'tm',
              s: { a: 0, k: 100, ix: 1 },
              e: { a: 0, k: 0, ix: 2 },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 2,
              nm: 'Recortar trazados 1',
              mn: 'ADBE Vector Filter - Trim',
              hd: false,
            },
          ],
          ip: 0,
          op: 125,
          st: 0,
          bm: 0,
        },
      ],
    },
  ],
  layers: [
    {
      ddd: 0,
      ind: 2,
      ty: 0,
      nm: 'Loading',
      refId: 'comp_0',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [540, 540, 0], ix: 2 },
        a: { a: 0, k: [540, 540, 0], ix: 1 },
        s: { a: 0, k: [90.37, 90.37, 100], ix: 6 },
      },
      ao: 0,
      w: 1080,
      h: 1080,
      ip: 0,
      op: 75,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
}
