name: Npm Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies, Build and Publish
        run: |
          npm install
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ github.sha }}
          API_BASE: "https://api.figni.io/api"
          WEBSOCKET_BASE: "wss://api.figni.io/ws"
      - name: slack notification on success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: figni-viewer release notification bot
          SLACK_ICON_EMOJI: ":figni:"
          SLACK_COLOR: good
          SLACK_MESSAGE: check out the release at https://www.npmjs.com/package/@cynack/figni-viewer
      - name: slack notification on failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: figni-viewer release notification bot
          SLACK_ICON_EMOJI: ":figni:"
          SLACK_COLOR: danger
          SLACK_MESSAGE: check out the problem at https://github.com/cynack/figni-viewer/actions
